-- Metodologia FII v4: observações PIT, exposições, snapshots e validação.
-- O schema market não é exposto pela Data API pública; acesso permanece server-side.

CREATE TABLE IF NOT EXISTS market.fii_methodology_versions (
    methodology_version text PRIMARY KEY,
    formula_version text NOT NULL,
    manifest_json jsonb NOT NULL,
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','validation','passed','retired')),
    created_at timestamptz NOT NULL DEFAULT now(),
    validated_at timestamptz
);

CREATE TABLE IF NOT EXISTS market.fii_metric_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    metric_name text NOT NULL,
    value_numeric numeric,
    value_text text,
    value_json jsonb,
    reference_date date NOT NULL,
    available_at timestamptz NOT NULL,
    vintage text NOT NULL,
    source text NOT NULL,
    source_url text,
    raw_payload_id bigint REFERENCES market.brapi_raw_payloads(id) ON DELETE SET NULL,
    quality_status text NOT NULL DEFAULT 'observed'
        CHECK (quality_status IN ('observed','validated','suspect','rejected')),
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    observed_at timestamptz NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(value_numeric, value_text, value_json) = 1),
    UNIQUE (ticker, metric_name, reference_date, available_at, vintage, source)
);
CREATE INDEX IF NOT EXISTS idx_fii_metric_pit
    ON market.fii_metric_observations (ticker, metric_name, available_at DESC);
CREATE INDEX IF NOT EXISTS idx_fii_metric_ref
    ON market.fii_metric_observations (reference_date, metric_name);

CREATE TABLE IF NOT EXISTS market.fii_exposures (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    exposure_type text NOT NULL CHECK (exposure_type IN
        ('manager','sector','tenant','debtor','issuer','indexer','region','holding')),
    exposure_name text NOT NULL,
    exposure_weight numeric NOT NULL CHECK (exposure_weight >= 0 AND exposure_weight <= 1),
    reference_date date NOT NULL,
    available_at timestamptz NOT NULL,
    vintage text NOT NULL,
    source text NOT NULL,
    raw_payload_id bigint REFERENCES market.brapi_raw_payloads(id) ON DELETE SET NULL,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (ticker, exposure_type, exposure_name, reference_date, available_at, vintage, source)
);
CREATE INDEX IF NOT EXISTS idx_fii_exposure_pit
    ON market.fii_exposures (ticker, exposure_type, available_at DESC);

CREATE TABLE IF NOT EXISTS market.fii_universe_history (
    ticker text NOT NULL,
    reference_date date NOT NULL,
    available_at timestamptz NOT NULL,
    active_status text NOT NULL CHECK (active_status IN ('listed','active','delisted','incorporated','liquidated')),
    successor_ticker text,
    source text NOT NULL,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (ticker, reference_date, available_at)
);

CREATE TABLE IF NOT EXISTS market.fii_validation_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    methodology_version text NOT NULL REFERENCES market.fii_methodology_versions(methodology_version),
    as_of_date date NOT NULL,
    status text NOT NULL CHECK (status IN ('running','passed','blocked','failed')),
    metrics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    blockers_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz
);

CREATE TABLE IF NOT EXISTS market.fii_score_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    reference_date date NOT NULL,
    available_at timestamptz NOT NULL,
    methodology_version text NOT NULL REFERENCES market.fii_methodology_versions(methodology_version),
    formula_version text NOT NULL,
    fii_type text NOT NULL CHECK (fii_type IN ('tijolo','papel','fof','hibrido')),
    type_score numeric NOT NULL CHECK (type_score BETWEEN 0 AND 100),
    confidence numeric NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    coverage numeric NOT NULL CHECK (coverage BETWEEN 0 AND 1),
    components_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    inputs_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    missing_metrics_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    publication_status text NOT NULL CHECK (publication_status IN ('diligence_only','validated')),
    publication_reasons_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    validation_run_id bigint REFERENCES market.fii_validation_runs(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (ticker, reference_date, available_at, methodology_version)
);
CREATE INDEX IF NOT EXISTS idx_fii_score_latest
    ON market.fii_score_snapshots (methodology_version, reference_date DESC, ticker);

CREATE TABLE IF NOT EXISTS market.fii_rebalance_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    detected_at timestamptz NOT NULL DEFAULT now(),
    event_type text NOT NULL,
    macro_regime_before text,
    macro_regime_after text,
    evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    decision text NOT NULL DEFAULT 'monitor' CHECK (decision IN ('monitor','rebalance','dismiss')),
    methodology_version text NOT NULL REFERENCES market.fii_methodology_versions(methodology_version)
);

INSERT INTO market.fii_methodology_versions
    (methodology_version, formula_version, manifest_json, status)
VALUES
    ('4.0.0', 'br-fii-income-resilience-4.0.0',
     '{"objective":"renda recorrente com crescimento patrimonial e resiliência","missing_data_policy":"never_zero_or_neutral","publication_policy":"diligence_only_until_pit_validation_passes"}'::jsonb,
     'validation')
ON CONFLICT (methodology_version) DO UPDATE SET
    formula_version = EXCLUDED.formula_version,
    manifest_json = EXCLUDED.manifest_json;
