-- Fundação de dados FII Pro: releases, bitemporalidade, qualidade e linhagem.
-- Idempotente e compatível com a migration 023.

ALTER TABLE market.fiis
    ADD COLUMN IF NOT EXISTS mandate text,
    ADD COLUMN IF NOT EXISTS administrator_name text,
    ADD COLUMN IF NOT EXISTS administrator_cnpj text;

ALTER TABLE market.brapi_raw_payloads
    ADD COLUMN IF NOT EXISTS request_fingerprint text,
    ADD COLUMN IF NOT EXISTS request_params_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS response_headers_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS content_sha256 text,
    ADD COLUMN IF NOT EXISTS http_status integer,
    ADD COLUMN IF NOT EXISTS source_published_at timestamptz,
    ADD COLUMN IF NOT EXISTS collected_at timestamptz,
    ADD COLUMN IF NOT EXISTS supersedes_id bigint REFERENCES market.brapi_raw_payloads(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS revision_detected boolean NOT NULL DEFAULT false;

UPDATE market.brapi_raw_payloads
SET collected_at = COALESCE(collected_at, fetched_at)
WHERE collected_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_brapi_raw_request
    ON market.brapi_raw_payloads (endpoint, request_fingerprint, collected_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_brapi_raw_success_content
    ON market.brapi_raw_payloads (endpoint, request_fingerprint, content_sha256)
    WHERE request_status = 'success' AND content_sha256 IS NOT NULL;

CREATE TABLE IF NOT EXISTS market.fii_source_releases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider text NOT NULL,
    endpoint text NOT NULL,
    natural_key text NOT NULL,
    reference_date date,
    source_published_at timestamptz,
    first_observed_at timestamptz NOT NULL,
    knowledge_at timestamptz NOT NULL,
    availability_quality text NOT NULL CHECK (availability_quality IN
        ('verified_publication','first_observed_proxy','retrospective_backfill','migration_baseline')),
    revision_no integer NOT NULL DEFAULT 1 CHECK (revision_no > 0),
    supersedes_id bigint REFERENCES market.fii_source_releases(id) ON DELETE SET NULL,
    raw_payload_id bigint NOT NULL REFERENCES market.brapi_raw_payloads(id) ON DELETE RESTRICT,
    content_sha256 text NOT NULL,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, endpoint, natural_key, revision_no),
    UNIQUE (provider, endpoint, natural_key, content_sha256)
);
CREATE INDEX IF NOT EXISTS idx_fii_source_release_pit
    ON market.fii_source_releases (provider, endpoint, natural_key, knowledge_at DESC);

ALTER TABLE market.fii_metric_observations
    ADD COLUMN IF NOT EXISTS source_published_at timestamptz,
    ADD COLUMN IF NOT EXISTS knowledge_at timestamptz,
    ADD COLUMN IF NOT EXISTS availability_quality text,
    ADD COLUMN IF NOT EXISTS content_hash text,
    ADD COLUMN IF NOT EXISTS source_release_id bigint REFERENCES market.fii_source_releases(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS supersedes_id bigint REFERENCES market.fii_metric_observations(id) ON DELETE SET NULL;

UPDATE market.fii_metric_observations
SET knowledge_at = COALESCE(knowledge_at, available_at),
    availability_quality = COALESCE(availability_quality, 'retrospective_backfill')
WHERE knowledge_at IS NULL OR availability_quality IS NULL;

ALTER TABLE market.fii_metric_observations
    ALTER COLUMN knowledge_at SET NOT NULL,
    ALTER COLUMN availability_quality SET NOT NULL;

ALTER TABLE market.fii_metric_observations
    DROP CONSTRAINT IF EXISTS fii_metric_observations_availability_quality_check;
ALTER TABLE market.fii_metric_observations
    ADD CONSTRAINT fii_metric_observations_availability_quality_check
    CHECK (availability_quality IN
        ('verified_publication','first_observed_proxy','retrospective_backfill','migration_baseline'));

CREATE INDEX IF NOT EXISTS idx_fii_metric_knowledge
    ON market.fii_metric_observations (ticker, metric_name, knowledge_at DESC, reference_date DESC);

ALTER TABLE market.fii_exposures
    ADD COLUMN IF NOT EXISTS source_published_at timestamptz,
    ADD COLUMN IF NOT EXISTS knowledge_at timestamptz,
    ADD COLUMN IF NOT EXISTS availability_quality text,
    ADD COLUMN IF NOT EXISTS content_hash text,
    ADD COLUMN IF NOT EXISTS source_release_id bigint REFERENCES market.fii_source_releases(id) ON DELETE SET NULL;

UPDATE market.fii_exposures
SET knowledge_at = COALESCE(knowledge_at, available_at),
    availability_quality = COALESCE(availability_quality, 'retrospective_backfill')
WHERE knowledge_at IS NULL OR availability_quality IS NULL;

ALTER TABLE market.fii_exposures
    ALTER COLUMN knowledge_at SET NOT NULL,
    ALTER COLUMN availability_quality SET NOT NULL;
ALTER TABLE market.fii_exposures
    DROP CONSTRAINT IF EXISTS fii_exposures_availability_quality_check;
ALTER TABLE market.fii_exposures
    ADD CONSTRAINT fii_exposures_availability_quality_check
    CHECK (availability_quality IN
        ('verified_publication','first_observed_proxy','retrospective_backfill','migration_baseline'));
ALTER TABLE market.fii_exposures
    DROP CONSTRAINT IF EXISTS fii_exposures_exposure_type_check;
ALTER TABLE market.fii_exposures
    ADD CONSTRAINT fii_exposures_exposure_type_check CHECK (exposure_type IN
        ('manager','sector','tenant','debtor','issuer','indexer','region','holding','asset_class'));
CREATE INDEX IF NOT EXISTS idx_fii_exposure_knowledge
    ON market.fii_exposures (ticker, exposure_type, knowledge_at DESC, reference_date DESC);

ALTER TABLE market.fii_universe_history
    ADD COLUMN IF NOT EXISTS knowledge_at timestamptz,
    ADD COLUMN IF NOT EXISTS availability_quality text,
    ADD COLUMN IF NOT EXISTS raw_payload_id bigint REFERENCES market.brapi_raw_payloads(id) ON DELETE SET NULL;
UPDATE market.fii_universe_history
SET knowledge_at = COALESCE(knowledge_at, available_at),
    availability_quality = COALESCE(availability_quality, 'retrospective_backfill')
WHERE knowledge_at IS NULL OR availability_quality IS NULL;
ALTER TABLE market.fii_universe_history
    ALTER COLUMN knowledge_at SET NOT NULL,
    ALTER COLUMN availability_quality SET NOT NULL;

CREATE TABLE IF NOT EXISTS market.fii_quality_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_type text NOT NULL DEFAULT 'ingestion',
    status text NOT NULL CHECK (status IN ('running','passed','blocked','failed')),
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    summary_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    correlation_id uuid
);

CREATE TABLE IF NOT EXISTS market.fii_quality_results (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL REFERENCES market.fii_quality_runs(id) ON DELETE CASCADE,
    rule_code text NOT NULL,
    entity_type text NOT NULL,
    entity_key text,
    severity text NOT NULL CHECK (severity IN ('info','low','medium','high','critical')),
    status text NOT NULL CHECK (status IN ('passed','warning','failed','quarantined')),
    observed_value jsonb NOT NULL DEFAULT '{}'::jsonb,
    message text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_fii_quality_results_run
    ON market.fii_quality_results (run_id, severity, status);

CREATE TABLE IF NOT EXISTS market.fii_reconciliation_issues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    metric_name text NOT NULL,
    reference_date date NOT NULL,
    left_source text NOT NULL,
    left_value jsonb,
    right_source text NOT NULL,
    right_value jsonb,
    absolute_difference numeric,
    relative_difference numeric,
    tolerance numeric,
    status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','accepted','resolved','rejected')),
    resolution_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    detected_at timestamptz NOT NULL DEFAULT now(),
    resolved_at timestamptz,
    UNIQUE (ticker, metric_name, reference_date, left_source, right_source)
);

CREATE TABLE IF NOT EXISTS market.fii_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type text NOT NULL,
    entity_type text NOT NULL,
    entity_id text,
    actor_type text NOT NULL DEFAULT 'service' CHECK (actor_type IN ('service','user','migration')),
    actor_id text,
    correlation_id uuid,
    algorithm_version text,
    parser_version text,
    git_sha text,
    payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_fii_audit_entity
    ON market.fii_audit_events (entity_type, entity_id, created_at DESC);

CREATE TABLE IF NOT EXISTS market.fii_lineage_edges (
    parent_type text NOT NULL,
    parent_id text NOT NULL,
    child_type text NOT NULL,
    child_id text NOT NULL,
    relation text NOT NULL,
    correlation_id uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (parent_type, parent_id, child_type, child_id, relation)
);

CREATE TABLE IF NOT EXISTS market.fii_parser_versions (
    parser_name text NOT NULL,
    parser_version text NOT NULL,
    schema_version text NOT NULL,
    code_sha256 text NOT NULL,
    status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','validation','active','retired')),
    config_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    activated_at timestamptz,
    PRIMARY KEY (parser_name, parser_version)
);

CREATE TABLE IF NOT EXISTS market.fii_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text,
    document_type text NOT NULL,
    natural_key text NOT NULL,
    reference_date date,
    source_published_at timestamptz,
    first_observed_at timestamptz NOT NULL,
    source_url text NOT NULL,
    current_version_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_type, natural_key)
);

CREATE TABLE IF NOT EXISTS market.fii_document_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL REFERENCES market.fii_documents(id) ON DELETE CASCADE,
    revision_no integer NOT NULL CHECK (revision_no > 0),
    content_sha256 text NOT NULL,
    storage_backend text NOT NULL CHECK (storage_backend IN ('supabase_storage','local_cache','remote_only')),
    storage_key text,
    mime_type text,
    byte_size bigint,
    page_count integer,
    downloaded_at timestamptz NOT NULL DEFAULT now(),
    supersedes_id bigint REFERENCES market.fii_document_versions(id) ON DELETE SET NULL,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (document_id, revision_no),
    UNIQUE (document_id, content_sha256)
);

DO $$ BEGIN
    ALTER TABLE market.fii_documents
        ADD CONSTRAINT fii_documents_current_version_fk
        FOREIGN KEY (current_version_id) REFERENCES market.fii_document_versions(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS market.fii_extraction_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id bigint NOT NULL REFERENCES market.fii_document_versions(id) ON DELETE CASCADE,
    parser_name text NOT NULL,
    parser_version text NOT NULL,
    status text NOT NULL CHECK (status IN ('running','passed','needs_review','failed')),
    text_method text,
    confidence numeric CHECK (confidence BETWEEN 0 AND 1),
    layout_signature text,
    metrics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    error_message text,
    FOREIGN KEY (parser_name, parser_version)
        REFERENCES market.fii_parser_versions(parser_name, parser_version)
);

CREATE TABLE IF NOT EXISTS market.fii_extraction_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extraction_run_id bigint NOT NULL REFERENCES market.fii_extraction_runs(id) ON DELETE CASCADE,
    metric_name text NOT NULL,
    raw_value text,
    normalized_value jsonb,
    unit text,
    page_number integer,
    bbox_json jsonb,
    evidence_text text NOT NULL,
    confidence numeric NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    validation_status text NOT NULL DEFAULT 'pending'
        CHECK (validation_status IN ('pending','accepted','corrected','rejected')),
    reviewer_id text,
    reviewed_at timestamptz,
    review_note text
);

COMMENT ON TABLE market.fii_source_releases IS
    'Versões imutáveis das releases de origem; knowledge_at controla elegibilidade PIT.';
COMMENT ON COLUMN market.fii_metric_observations.knowledge_at IS
    'Primeiro instante defensável em que esta versão específica podia ser conhecida.';
COMMENT ON COLUMN market.fii_metric_observations.availability_quality IS
    'Qualidade da evidência temporal; backfills retrospectivos não são PIT histórico.';
