-- Evolucao da confiabilidade dos FIIs: historico diario auditavel, look-through
-- de CRIs e fila concorrente para documentos publicos.
-- O schema market permanece backend-only e fechado para a Data API.

ALTER TABLE market.historical_prices
    ADD COLUMN IF NOT EXISTS source text,
    ADD COLUMN IF NOT EXISTS raw_payload_id bigint
        REFERENCES market.brapi_raw_payloads(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS knowledge_at timestamptz,
    ADD COLUMN IF NOT EXISTS availability_quality text,
    ADD COLUMN IF NOT EXISTS content_hash text;

UPDATE market.historical_prices
SET source = COALESCE(source, 'brapi_legacy_quote'),
    knowledge_at = COALESCE(knowledge_at, updated_at, now()),
    availability_quality = COALESCE(availability_quality, 'retrospective_backfill')
WHERE source IS NULL OR knowledge_at IS NULL OR availability_quality IS NULL;

ALTER TABLE market.historical_prices
    ALTER COLUMN source SET DEFAULT 'brapi_legacy_quote',
    ALTER COLUMN source SET NOT NULL,
    ALTER COLUMN knowledge_at SET DEFAULT now(),
    ALTER COLUMN knowledge_at SET NOT NULL,
    ALTER COLUMN availability_quality SET DEFAULT 'first_observed_proxy',
    ALTER COLUMN availability_quality SET NOT NULL;

ALTER TABLE market.historical_prices
    DROP CONSTRAINT IF EXISTS historical_prices_availability_quality_check;
ALTER TABLE market.historical_prices
    ADD CONSTRAINT historical_prices_availability_quality_check
    CHECK (availability_quality IN
        ('verified_publication','first_observed_proxy','retrospective_backfill','migration_baseline'));

CREATE INDEX IF NOT EXISTS idx_historical_prices_pit
    ON market.historical_prices (ticker, knowledge_at DESC, date DESC);
CREATE INDEX IF NOT EXISTS idx_historical_prices_raw_payload
    ON market.historical_prices (raw_payload_id)
    WHERE raw_payload_id IS NOT NULL;

-- A tabela historica legada continua como estado corrente para compatibilidade.
-- Esta tabela append-only preserva cada revisao observada e e a fonte correta
-- para reconstrucoes point-in-time.
CREATE TABLE IF NOT EXISTS market.historical_price_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL REFERENCES market.assets(ticker) ON DELETE CASCADE,
    date date NOT NULL,
    open numeric(18,6),
    high numeric(18,6),
    low numeric(18,6),
    close numeric(18,6) NOT NULL CHECK (close > 0),
    adjusted_close numeric(18,6),
    volume bigint,
    source text NOT NULL,
    raw_payload_id bigint REFERENCES market.brapi_raw_payloads(id) ON DELETE SET NULL,
    available_at timestamptz NOT NULL,
    knowledge_at timestamptz NOT NULL,
    availability_quality text NOT NULL CHECK (availability_quality IN
        ('verified_publication','first_observed_proxy','retrospective_backfill','migration_baseline')),
    content_hash text NOT NULL,
    observed_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (ticker, date, source, content_hash)
);

INSERT INTO market.historical_price_observations (
    ticker,date,open,high,low,close,adjusted_close,volume,source,
    raw_payload_id,available_at,knowledge_at,availability_quality,content_hash
)
SELECT ticker,date,open,high,low,close,adjusted_close,volume,source,
       raw_payload_id,knowledge_at,knowledge_at,availability_quality,
       COALESCE(content_hash,
                md5(concat_ws('|',ticker,date,open,high,low,close,
                              adjusted_close,volume,source)))
FROM market.historical_prices
WHERE close > 0
ON CONFLICT DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_historical_price_observations_pit
    ON market.historical_price_observations
       (ticker, date, knowledge_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_historical_price_observations_raw
    ON market.historical_price_observations (raw_payload_id)
    WHERE raw_payload_id IS NOT NULL;

ALTER TABLE market.historical_price_observations ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE market.historical_price_observations
    FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE market.historical_price_observations_id_seq
    FROM PUBLIC, anon, authenticated;
DROP POLICY IF EXISTS data_api_private_deny ON market.historical_price_observations;
CREATE POLICY data_api_private_deny
    ON market.historical_price_observations AS RESTRICTIVE
    FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);

ALTER TABLE market.fii_exposures
    DROP CONSTRAINT IF EXISTS fii_exposures_exposure_type_check;
ALTER TABLE market.fii_exposures
    ADD CONSTRAINT fii_exposures_exposure_type_check CHECK (exposure_type IN
        ('manager','sector','tenant','debtor','issuer','indexer','region',
         'holding','security','asset_class'));

CREATE TABLE IF NOT EXISTS market.cri_security_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_key text NOT NULL,
    issuer_cnpj text NOT NULL,
    certificate_code text,
    issue_number text,
    series_number text,
    metric_name text NOT NULL,
    value_numeric numeric,
    value_text text,
    value_json jsonb,
    reference_date date NOT NULL,
    available_at timestamptz NOT NULL,
    source_published_at timestamptz,
    knowledge_at timestamptz NOT NULL,
    availability_quality text NOT NULL CHECK (availability_quality IN
        ('verified_publication','first_observed_proxy','retrospective_backfill','migration_baseline')),
    vintage text NOT NULL,
    source text NOT NULL,
    source_url text,
    raw_payload_id bigint REFERENCES market.brapi_raw_payloads(id) ON DELETE SET NULL,
    source_release_id bigint REFERENCES market.fii_source_releases(id) ON DELETE SET NULL,
    content_hash text NOT NULL,
    quality_status text NOT NULL DEFAULT 'observed'
        CHECK (quality_status IN ('observed','accepted','suspect','rejected')),
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    observed_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (security_key, metric_name, reference_date, available_at, vintage, source)
);

CREATE INDEX IF NOT EXISTS idx_cri_security_metric_pit
    ON market.cri_security_observations
       (security_key, metric_name, knowledge_at DESC, reference_date DESC);
CREATE INDEX IF NOT EXISTS idx_cri_security_issuer_issue
    ON market.cri_security_observations
       (issuer_cnpj, issue_number, series_number, reference_date DESC);
CREATE INDEX IF NOT EXISTS idx_cri_security_raw_payload
    ON market.cri_security_observations (raw_payload_id)
    WHERE raw_payload_id IS NOT NULL;

ALTER TABLE market.cri_security_observations ENABLE ROW LEVEL SECURITY;
REVOKE ALL PRIVILEGES ON TABLE market.cri_security_observations
    FROM PUBLIC, anon, authenticated;
REVOKE ALL PRIVILEGES ON SEQUENCE market.cri_security_observations_id_seq
    FROM PUBLIC, anon, authenticated;

DROP POLICY IF EXISTS data_api_private_deny ON market.cri_security_observations;
CREATE POLICY data_api_private_deny
    ON market.cri_security_observations AS RESTRICTIVE
    FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);

ALTER TABLE market.fii_documents
    ADD COLUMN IF NOT EXISTS processing_status text NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS processing_started_at timestamptz,
    ADD COLUMN IF NOT EXISTS processing_worker text,
    ADD COLUMN IF NOT EXISTS processing_attempts integer NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS next_retry_at timestamptz,
    ADD COLUMN IF NOT EXISTS last_error text;

ALTER TABLE market.fii_documents
    DROP CONSTRAINT IF EXISTS fii_documents_processing_status_check;
ALTER TABLE market.fii_documents
    ADD CONSTRAINT fii_documents_processing_status_check
    CHECK (processing_status IN
        ('pending','processing','completed','needs_review','failed'));

WITH latest_success AS (
    SELECT DISTINCT ON (dv.document_id)
           dv.document_id, er.status
    FROM market.fii_document_versions dv
    JOIN market.fii_extraction_runs er ON er.document_version_id = dv.id
    WHERE er.status IN ('passed','needs_review')
    ORDER BY dv.document_id, er.finished_at DESC NULLS LAST, er.id DESC
)
UPDATE market.fii_documents d
SET processing_status = CASE
        WHEN r.status = 'needs_review' THEN 'needs_review'
        ELSE 'completed'
    END,
    processing_started_at = NULL,
    processing_worker = NULL,
    last_error = NULL
FROM latest_success r
WHERE r.document_id = d.id;

CREATE INDEX IF NOT EXISTS idx_fii_documents_processing_queue
    ON market.fii_documents
       (processing_status, next_retry_at, reference_date DESC, id DESC)
    WHERE processing_status IN ('pending','failed','processing');

COMMENT ON TABLE market.cri_security_observations IS
    'Observacoes PIT por CRI da CVM; somente agregados com cobertura suficiente podem alimentar scores de FIIs.';
COMMENT ON COLUMN market.historical_prices.knowledge_at IS
    'Primeiro instante defensavel em que esta versao do preco podia ser conhecida pelo sistema.';
COMMENT ON TABLE market.historical_price_observations IS
    'Historico append-only de versoes OHLCV; usar knowledge_at para reconstrucoes e backtests PIT.';
