-- Metodologia FII v6: universo histórico B3/CVM, reconstrução PIT, backtest,
-- entidades canônicas, calibração humana e monitoramento. Todas as tabelas são
-- backend-only; RLS e REVOKE impedem exposição pela Data API/GraphQL.

INSERT INTO market.fii_methodology_versions
    (methodology_version, formula_version, manifest_json, status)
VALUES (
    '6.0.0', 'br-fii-integrated-income-resilience-6.0.0',
    '{
      "objective":"renda recorrente com crescimento patrimonial e resiliencia",
      "stages":["eligibility","type_score","empirical_confidence","pit_walk_forward","robust_scenario_optimization"],
      "confidence":"coverage+freshness+source+consistency+history+human_calibration",
      "publication_policy":"diligence_only_until_point_in_time_validation_passes"
    }'::jsonb, 'validation'
)
ON CONFLICT (methodology_version) DO UPDATE SET
    formula_version=EXCLUDED.formula_version,
    manifest_json=EXCLUDED.manifest_json,
    status=CASE WHEN market.fii_methodology_versions.status='passed'
                THEN 'passed' ELSE EXCLUDED.status END;

CREATE TABLE IF NOT EXISTS market.fii_registry_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj text NOT NULL,
    cvm_code text,
    fund_registry_id text,
    class_registry_id text,
    ticker text,
    legal_name text,
    fund_type text,
    classification text,
    status text NOT NULL,
    registration_date date,
    constitution_date date,
    start_date date,
    cancellation_date date,
    manager_identifier text,
    manager_name text,
    administrator_identifier text,
    administrator_name text,
    reference_date date NOT NULL,
    collected_at timestamptz NOT NULL,
    source text NOT NULL,
    raw_payload_id bigint REFERENCES market.brapi_raw_payloads(id) ON DELETE SET NULL,
    content_hash text NOT NULL,
    raw_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (cnpj ~ '^[0-9]{14}$'),
    CHECK (cancellation_date IS NULL OR start_date IS NULL OR cancellation_date >= start_date),
    UNIQUE (cnpj, reference_date, content_hash)
);
CREATE INDEX IF NOT EXISTS idx_fii_registry_lifecycle
    ON market.fii_registry_observations (ticker, start_date, cancellation_date);
CREATE INDEX IF NOT EXISTS idx_fii_registry_cnpj_latest
    ON market.fii_registry_observations (cnpj, reference_date DESC, collected_at DESC);
CREATE INDEX IF NOT EXISTS idx_fii_registry_raw
    ON market.fii_registry_observations (raw_payload_id) WHERE raw_payload_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS market.fii_b3_security_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    trade_date date NOT NULL,
    issuer_short_name text,
    specification text,
    isin text,
    open numeric(18,6), high numeric(18,6), low numeric(18,6),
    average numeric(18,6), close numeric(18,6) NOT NULL CHECK (close > 0),
    trades integer, quantity bigint, financial_volume numeric(22,2),
    source text NOT NULL,
    source_url text NOT NULL,
    raw_payload_id bigint REFERENCES market.brapi_raw_payloads(id) ON DELETE SET NULL,
    collected_at timestamptz NOT NULL,
    archive_sha256 text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (ticker, trade_date, archive_sha256)
);
CREATE INDEX IF NOT EXISTS idx_fii_b3_history_ticker_date
    ON market.fii_b3_security_history (ticker, trade_date);
CREATE INDEX IF NOT EXISTS idx_fii_b3_history_isin
    ON market.fii_b3_security_history (isin, trade_date) WHERE isin IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_fii_b3_history_raw
    ON market.fii_b3_security_history (raw_payload_id) WHERE raw_payload_id IS NOT NULL;

CREATE OR REPLACE FUNCTION market.normalize_fii_entity_name(value text)
RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE
SET search_path = ''
AS $$
  SELECT trim(regexp_replace(
    translate(lower(coalesce(value,'')),
      'áàâãäéèêëíìîïóòôõöúùûüç',
      'aaaaaeeeeiiiiooooouuuuc'),
    '[^a-z0-9]+', ' ', 'g'));
$$;
REVOKE ALL ON FUNCTION market.normalize_fii_entity_name(text) FROM PUBLIC, anon, authenticated;

CREATE TABLE IF NOT EXISTS market.fii_canonical_entities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type text NOT NULL CHECK (entity_type IN
        ('tenant','debtor','issuer','manager','holding','security','property','fund')),
    canonical_name text NOT NULL,
    normalized_name text NOT NULL,
    legal_identifier text,
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','merged','inactive')),
    successor_id bigint REFERENCES market.fii_canonical_entities(id) ON DELETE SET NULL,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (entity_type, normalized_name)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fii_canonical_entity_identifier
    ON market.fii_canonical_entities (entity_type, legal_identifier)
    WHERE legal_identifier IS NOT NULL;

CREATE TABLE IF NOT EXISTS market.fii_entity_aliases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type text NOT NULL,
    alias_name text NOT NULL,
    normalized_alias text NOT NULL,
    legal_identifier text NOT NULL DEFAULT '',
    canonical_entity_id bigint REFERENCES market.fii_canonical_entities(id) ON DELETE SET NULL,
    match_method text NOT NULL,
    match_confidence numeric NOT NULL CHECK (match_confidence BETWEEN 0 AND 1),
    validation_status text NOT NULL CHECK (validation_status IN
        ('proposed','accepted','rejected','unresolved')),
    evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    reviewer_id text,
    reviewed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (entity_type, normalized_alias, legal_identifier)
);
CREATE INDEX IF NOT EXISTS idx_fii_canonical_successor
    ON market.fii_canonical_entities (successor_id) WHERE successor_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_fii_entity_alias_review
    ON market.fii_entity_aliases (validation_status, match_confidence DESC);
CREATE INDEX IF NOT EXISTS idx_fii_entity_alias_canonical
    ON market.fii_entity_aliases (canonical_entity_id) WHERE canonical_entity_id IS NOT NULL;

ALTER TABLE market.fii_exposures
    ADD COLUMN IF NOT EXISTS canonical_entity_id bigint
        REFERENCES market.fii_canonical_entities(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS entity_match_confidence numeric
        CHECK (entity_match_confidence BETWEEN 0 AND 1);
CREATE INDEX IF NOT EXISTS idx_fii_exposure_canonical
    ON market.fii_exposures (exposure_type, canonical_entity_id, reference_date DESC)
    WHERE canonical_entity_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS market.fii_parser_calibrations (
    parser_name text NOT NULL,
    parser_version text NOT NULL,
    metric_name text NOT NULL,
    reviewed_count integer NOT NULL CHECK (reviewed_count >= 0),
    accepted_count integer NOT NULL CHECK (accepted_count >= 0),
    corrected_count integer NOT NULL CHECK (corrected_count >= 0),
    rejected_count integer NOT NULL CHECK (rejected_count >= 0),
    posterior_mean numeric NOT NULL CHECK (posterior_mean BETWEEN 0 AND 1),
    lower_bound numeric NOT NULL CHECK (lower_bound BETWEEN 0 AND 1),
    upper_bound numeric NOT NULL CHECK (upper_bound BETWEEN 0 AND 1),
    calibrated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (parser_name, parser_version, metric_name),
    CHECK (lower_bound <= posterior_mean AND posterior_mean <= upper_bound),
    CHECK (reviewed_count = accepted_count + corrected_count + rejected_count)
);

CREATE TABLE IF NOT EXISTS market.fii_pit_score_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL,
    reference_date date NOT NULL,
    available_at timestamptz NOT NULL,
    methodology_version text NOT NULL REFERENCES market.fii_methodology_versions(methodology_version),
    formula_version text NOT NULL,
    fii_type text NOT NULL CHECK (fii_type IN ('tijolo','papel','fof','hibrido')),
    type_score numeric NOT NULL CHECK (type_score BETWEEN 0 AND 100),
    confidence numeric NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    coverage numeric NOT NULL CHECK (coverage BETWEEN 0 AND 1),
    critical_coverage numeric NOT NULL CHECK (critical_coverage BETWEEN 0 AND 1),
    availability_quality text NOT NULL CHECK (availability_quality IN
        ('verified_publication','market_close_observable','first_observed_proxy','retrospective_backfill')),
    components_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    inputs_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    missing_metrics_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    data_readiness_status text NOT NULL CHECK (data_readiness_status IN ('ready','insufficient')),
    reconstructed_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (ticker, reference_date, methodology_version, formula_version)
);
CREATE INDEX IF NOT EXISTS idx_fii_pit_snapshot_decision
    ON market.fii_pit_score_snapshots (methodology_version, reference_date, type_score DESC);
CREATE INDEX IF NOT EXISTS idx_fii_pit_snapshot_available
    ON market.fii_pit_score_snapshots (available_at, availability_quality);

CREATE TABLE IF NOT EXISTS market.fii_backtest_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    validation_run_id bigint REFERENCES market.fii_validation_runs(id) ON DELETE SET NULL,
    methodology_version text NOT NULL REFERENCES market.fii_methodology_versions(methodology_version),
    formula_version text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    rebalance_frequency text NOT NULL,
    benchmark_name text NOT NULL,
    top_n integer NOT NULL CHECK (top_n > 0),
    transaction_cost numeric NOT NULL CHECK (transaction_cost >= 0),
    slippage numeric NOT NULL CHECK (slippage >= 0),
    status text NOT NULL CHECK (status IN ('running','passed','blocked','failed')),
    metrics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    blockers_json jsonb NOT NULL DEFAULT '[]'::jsonb,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    CHECK (end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS idx_fii_backtest_latest
    ON market.fii_backtest_runs (methodology_version, finished_at DESC);
CREATE INDEX IF NOT EXISTS idx_fii_backtest_validation
    ON market.fii_backtest_runs (validation_run_id) WHERE validation_run_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS market.fii_backtest_periods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backtest_run_id bigint NOT NULL REFERENCES market.fii_backtest_runs(id) ON DELETE CASCADE,
    decision_date date NOT NULL,
    execution_date date NOT NULL,
    portfolio_return numeric,
    benchmark_return numeric,
    coverage numeric CHECK (coverage BETWEEN 0 AND 1),
    turnover numeric CHECK (turnover >= 0),
    holdings_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (backtest_run_id, decision_date)
);

CREATE TABLE IF NOT EXISTS market.fii_backtest_positions (
    backtest_run_id bigint NOT NULL REFERENCES market.fii_backtest_runs(id) ON DELETE CASCADE,
    decision_date date NOT NULL,
    ticker text NOT NULL,
    weight numeric NOT NULL CHECK (weight > 0 AND weight <= 1),
    PRIMARY KEY (backtest_run_id, decision_date, ticker)
);

CREATE TABLE IF NOT EXISTS market.fii_pipeline_alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_code text NOT NULL,
    severity text NOT NULL CHECK (severity IN ('info','low','medium','high','critical')),
    status text NOT NULL CHECK (status IN ('passed','warning','failed')),
    observed_value jsonb NOT NULL DEFAULT '{}'::jsonb,
    message text NOT NULL,
    first_seen_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    occurrences integer NOT NULL DEFAULT 1 CHECK (occurrences > 0),
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    resolved_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_fii_pipeline_alert_open
    ON market.fii_pipeline_alerts (alert_code, status) WHERE resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_fii_pipeline_alert_status
    ON market.fii_pipeline_alerts (resolved_at, severity, last_seen_at DESC);

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'fii_registry_observations','fii_b3_security_history','fii_canonical_entities',
    'fii_entity_aliases','fii_parser_calibrations','fii_pit_score_snapshots',
    'fii_backtest_runs','fii_backtest_periods','fii_backtest_positions',
    'fii_pipeline_alerts'
  ] LOOP
    EXECUTE format('ALTER TABLE market.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('REVOKE ALL PRIVILEGES ON TABLE market.%I FROM PUBLIC, anon, authenticated', table_name);
    EXECUTE format('DROP POLICY IF EXISTS data_api_private_deny ON market.%I', table_name);
    EXECUTE format('CREATE POLICY data_api_private_deny ON market.%I AS RESTRICTIVE FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)', table_name);
  END LOOP;
END $$;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA market FROM PUBLIC, anon, authenticated;

COMMENT ON TABLE market.fii_pit_score_snapshots IS
    'Scores históricos reconstruídos somente com dados elegíveis pelo knowledge_at da decisão.';
COMMENT ON TABLE market.fii_b3_security_history IS
    'Security master e cotações oficiais B3 sem ajuste por proventos; preserva fundos fora do universo atual.';
COMMENT ON TABLE market.fii_parser_calibrations IS
    'Acurácia posterior por parser/métrica calculada apenas a partir de revisão humana.';
