-- Fontes oficiais de documentos e observações granulares de empreendimentos FII.
-- O schema market é backend-only. Extrações entram pendentes e não alimentam
-- scores nem recomendações antes de revisão humana ou reconciliação explícita.

CREATE TABLE IF NOT EXISTS market.fii_document_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text REFERENCES market.fiis(ticker) ON DELETE CASCADE,
    cnpj text,
    source_type text NOT NULL CHECK (source_type IN ('cvm','fundos_net','ri_manager','ri_administrator')),
    official_name text NOT NULL,
    base_url text NOT NULL,
    documents_url text NOT NULL,
    allowed_host text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    collection_interval_hours integer NOT NULL DEFAULT 24
        CHECK (collection_interval_hours BETWEEN 1 AND 8760),
    last_checked_at timestamptz,
    last_success_at timestamptz,
    last_error text,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_type, documents_url)
);

CREATE INDEX IF NOT EXISTS idx_fii_document_sources_due
    ON market.fii_document_sources (last_checked_at NULLS FIRST, id)
    WHERE enabled;
CREATE INDEX IF NOT EXISTS idx_fii_document_sources_ticker
    ON market.fii_document_sources (ticker, source_type)
    WHERE ticker IS NOT NULL;

CREATE TABLE IF NOT EXISTS market.fii_projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker text NOT NULL REFERENCES market.fiis(ticker) ON DELETE CASCADE,
    project_key text NOT NULL,
    project_name text NOT NULL,
    normalized_name text NOT NULL,
    city text,
    state char(2),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (ticker, project_key)
);

CREATE INDEX IF NOT EXISTS idx_fii_projects_ticker_name
    ON market.fii_projects (ticker, normalized_name);

CREATE TABLE IF NOT EXISTS market.fii_project_observations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES market.fii_projects(id) ON DELETE CASCADE,
    document_version_id bigint NOT NULL
        REFERENCES market.fii_document_versions(id) ON DELETE CASCADE,
    extraction_run_id bigint NOT NULL
        REFERENCES market.fii_extraction_runs(id) ON DELETE CASCADE,
    reference_date date NOT NULL,
    source_published_at timestamptz,
    knowledge_at timestamptz NOT NULL,
    project_type text,
    stage text,
    portfolio_weight numeric CHECK (portfolio_weight BETWEEN 0 AND 1),
    construction_progress numeric CHECK (construction_progress BETWEEN 0 AND 1),
    sales_progress numeric CHECK (sales_progress BETWEEN 0 AND 1),
    expected_irr numeric CHECK (expected_irr BETWEEN -1 AND 10),
    expected_result_brl numeric,
    vgv_brl numeric CHECK (vgv_brl >= 0),
    sellable_area_sqm numeric CHECK (sellable_area_sqm >= 0),
    unit_count integer CHECK (unit_count >= 0),
    financing_type text,
    market_standard text,
    value_nature text NOT NULL DEFAULT 'manager_reported'
        CHECK (value_nature IN (
            'audited','regulatory_filing','manager_reported',
            'manager_estimate','derived'
        )),
    raw_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    page_number integer,
    evidence_text text NOT NULL,
    confidence numeric NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    validation_status text NOT NULL DEFAULT 'pending'
        CHECK (validation_status IN (
            'pending','accepted','corrected','rejected','conflicting'
        )),
    validation_method text NOT NULL DEFAULT 'pending'
        CHECK (validation_method IN (
            'pending','human','cross_source','parser_rule'
        )),
    reviewer_id text,
    reviewed_at timestamptz,
    review_note text,
    review_hash text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, reference_date, document_version_id)
);

CREATE INDEX IF NOT EXISTS idx_fii_project_observations_project_pit
    ON market.fii_project_observations
       (project_id, knowledge_at DESC, reference_date DESC);
CREATE INDEX IF NOT EXISTS idx_fii_project_observations_document
    ON market.fii_project_observations (document_version_id);
CREATE INDEX IF NOT EXISTS idx_fii_project_observations_run
    ON market.fii_project_observations (extraction_run_id);
CREATE INDEX IF NOT EXISTS idx_fii_project_review_queue
    ON market.fii_project_observations
       (validation_status, confidence DESC, reference_date DESC, id)
    WHERE validation_status IN ('pending','conflicting');

CREATE TABLE IF NOT EXISTS market.fii_document_findings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id bigint NOT NULL
        REFERENCES market.fii_document_versions(id) ON DELETE CASCADE,
    extraction_run_id bigint NOT NULL
        REFERENCES market.fii_extraction_runs(id) ON DELETE CASCADE,
    ticker text REFERENCES market.fiis(ticker) ON DELETE CASCADE,
    reference_date date,
    finding_type text NOT NULL CHECK (finding_type IN (
        'reported_fact','manager_estimate','manager_view','risk','opportunity'
    )),
    topic text NOT NULL,
    claim_text text NOT NULL,
    page_number integer,
    confidence numeric NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    validation_status text NOT NULL DEFAULT 'pending'
        CHECK (validation_status IN (
            'pending','accepted','corrected','rejected','conflicting'
        )),
    validation_method text NOT NULL DEFAULT 'pending'
        CHECK (validation_method IN (
            'pending','human','cross_source','parser_rule'
        )),
    reviewer_id text,
    reviewed_at timestamptz,
    review_note text,
    review_hash text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_version_id, finding_type, topic, page_number, claim_text)
);

CREATE INDEX IF NOT EXISTS idx_fii_document_findings_ticker
    ON market.fii_document_findings (ticker, reference_date DESC, topic);
CREATE INDEX IF NOT EXISTS idx_fii_document_findings_review_queue
    ON market.fii_document_findings
       (validation_status, confidence DESC, reference_date DESC, id)
    WHERE validation_status IN ('pending','conflicting');
CREATE INDEX IF NOT EXISTS idx_fii_document_findings_version
    ON market.fii_document_findings (document_version_id);
CREATE INDEX IF NOT EXISTS idx_fii_document_findings_run
    ON market.fii_document_findings (extraction_run_id);

ALTER TABLE market.fii_extraction_evidence
    ADD COLUMN IF NOT EXISTS value_nature text NOT NULL DEFAULT 'manager_reported',
    ADD COLUMN IF NOT EXISTS review_priority smallint NOT NULL DEFAULT 50
        CHECK (review_priority BETWEEN 0 AND 100);

ALTER TABLE market.fii_extraction_evidence
    DROP CONSTRAINT IF EXISTS fii_extraction_evidence_value_nature_check;
ALTER TABLE market.fii_extraction_evidence
    ADD CONSTRAINT fii_extraction_evidence_value_nature_check
    CHECK (value_nature IN (
        'audited','regulatory_filing','manager_reported',
        'manager_estimate','derived'
    ));

CREATE INDEX IF NOT EXISTS idx_fii_evidence_priority_queue
    ON market.fii_extraction_evidence
       (review_priority DESC, confidence DESC, id)
    WHERE validation_status='pending';

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'fii_document_sources','fii_projects','fii_project_observations',
    'fii_document_findings'
  ] LOOP
    EXECUTE format('ALTER TABLE market.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format(
      'REVOKE ALL PRIVILEGES ON TABLE market.%I FROM PUBLIC, anon, authenticated',
      table_name
    );
    EXECUTE format('DROP POLICY IF EXISTS data_api_private_deny ON market.%I', table_name);
    EXECUTE format(
      'CREATE POLICY data_api_private_deny ON market.%I AS RESTRICTIVE '
      'FOR ALL TO anon, authenticated USING (false) WITH CHECK (false)',
      table_name
    );
  END LOOP;
END $$;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA market
    FROM PUBLIC, anon, authenticated;

COMMENT ON TABLE market.fii_document_sources IS
    'Allowlist de páginas oficiais CVM/Fundos.NET/RI usadas pelo coletor documental.';
COMMENT ON TABLE market.fii_project_observations IS
    'Observações bitemporais por empreendimento; estimativas do gestor ficam explicitamente rotuladas.';
COMMENT ON TABLE market.fii_document_findings IS
    'Afirmações qualitativas com evidência de página; não entram automaticamente em cálculos.';

INSERT INTO market.fii_schema_migrations(version) VALUES ('046')
ON CONFLICT (version) DO UPDATE SET applied_at=EXCLUDED.applied_at;
