"""Preco diario de acoes da B3 no armazem local, a partir do COTAHIST.

Por que este modulo existe
--------------------------
A serie de precos de acoes da B3 que o armazem tinha ate aqui é
`market.historical_prices`: 137.735 linhas em **1.542 datas** cobrindo
2000-2026 -- cerca de 24 pregoes por ano ate 2013. Ela vem de cotacao pontual
da brapi, nao de arquivo de pregao. Uma funcao que receba essa serie e devolva
"retorno em 1 pregao" devolve, na pratica, retorno de duas semanas: sem erro,
sem aviso, com o rotulo errado. `core.memoria_mercado.serie` defende-se disso
com o portao de densidade, e o preco de estar certo era responder ``None`` para
todo horizonte curto da B3.

O arquivo que resolve isso ja estava no disco. O COTAHIST que a ingestao de
FIIs baixa desde julho traz **todos** os papeis do pregao na mesma linha de 245
colunas; a ingestao antiga lia o ano inteiro e jogava fora tudo que nao fosse
BDI 12. Este modulo aproveita a outra fatia -- BDI 02, lote padrao -- e grava
1,6 milhao de linhas em 4.099 pregoes, serie diaria de fato.

O que entra
-----------
BDI 02, mercado a vista (TPMERC 010). Isso inclui acoes ON/PN/UNT e tambem
BDRs (especificacao DRN/DR1/DR3) e ETFs, que negociam no mesmo lote padrao. A
composicao muda muito por ano -- em 2021, 101.581 das 195.326 linhas sao DRN --
entao `specification` viaja junto e quem quiser so acao brasileira filtra na
leitura. Chamar o conjunto de "acoes" sem essa ressalva seria rotulo errado.

Fator de cotacao
----------------
`PREULT` é o preco de **`FATCOT` unidades** do papel, e `FATCOT` nao é sempre
1: 1.074 linhas de 2013 e 203 de 2025 valem por lote de 100 ou 1.000. Gravar o
fechamento cru como se fosse preco unitario introduz um erro de 1000x que nao
levanta excecao nenhuma. A tabela guarda os dois: `close` como o arquivo traz e
`close_unitario` = `close / fator_cotacao`, que é o que a serie de retorno deve
ler.

Onde grava
----------
**So no armazem local.** Sao ~1 GB; o Supabase esta em 425 MB de 500 MB e
derruba-lo derruba o app publicado. O DDL mora aqui, e nao em
`supabase_unificado/schema/`, pelo mesmo motivo que o da Memoria de Mercado
mora em `core.memoria_mercado.repositorio`: aquele diretorio é aplicado no
Supabase.

O arquivo nao é ajustado por proventos. É preco negociado e prova de que o
papel existia na data -- nao serie de retorno total.
"""
from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import text

from data_pipeline.market import b3_cotahist
from data_pipeline.market.fii_b3_history import fetch_year
from data_pipeline.market.repository import save_raw_payload

SOURCE = "b3_cotahist"
PARSER_NAME = "b3_cotahist_lote_padrao"
PARSER_VERSION = "1.0.0"
PARSER_SCHEMA_VERSION = "cotahist-layout-2020-r2"
#: Primeiro ano de COTAHIST que a ingestao de FIIs ja deixou em disco.
PRIMEIRO_ANO = 2010
_LOGGER = logging.getLogger(__name__)
_BATCH_SIZE = 5_000

#: Hosts aceitos como armazem local. Mesma lista de
#: `core.memoria_mercado.repositorio`, pelo mesmo motivo.
HOSTS_LOCAIS = {"localhost", "127.0.0.1", "::1", "host.docker.internal"}

# A identidade de um preco é `(ticker, trade_date)`, nao `(ticker, trade_date,
# archive_sha256)`. A diferenca nao é cosmetica: o COTAHIST do ano corrente muda
# de conteudo -- e portanto de sha -- a cada dia de pregao, entao uma chave que
# inclua o sha aceita o ano inteiro de novo a cada rebaixa. Em 2026 isso seriam
# 43 mil linhas duplicadas por dia, cada pregao com N copias identicas, e
# qualquer retorno ou media lido daqui sairia errado sem nenhuma excecao. O sha
# é procedencia: diz de qual arquivo a linha veio, nao qual linha ela é.
DDL = (
    """
    CREATE TABLE IF NOT EXISTS market.b3_security_history (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ticker text NOT NULL,
        trade_date date NOT NULL,
        bdi text NOT NULL,
        issuer_short_name text,
        specification text,
        isin text,
        open numeric(18,6), high numeric(18,6), low numeric(18,6),
        average numeric(18,6),
        close numeric(18,6) NOT NULL CHECK (close > 0),
        fator_cotacao integer,
        close_unitario numeric(18,6) NOT NULL CHECK (close_unitario > 0),
        trades integer, quantity bigint, financial_volume numeric(22,2),
        source text NOT NULL,
        source_url text NOT NULL,
        raw_payload_id bigint,
        collected_at timestamptz NOT NULL,
        archive_sha256 text NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT b3_security_history_ticker_data_key UNIQUE (ticker, trade_date)
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_b3_history_ticker_date
        ON market.b3_security_history (ticker, trade_date)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_b3_history_date
        ON market.b3_security_history (trade_date)
    """,
    """
    CREATE TABLE IF NOT EXISTS market.b3_archive_loads (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        archive_year integer NOT NULL,
        archive_sha256 text NOT NULL,
        parser_name text NOT NULL,
        parser_version text NOT NULL,
        source_url text NOT NULL,
        expected_rows integer NOT NULL,
        loaded_rows integer NOT NULL DEFAULT 0,
        status text NOT NULL CHECK (status IN ('running','completed','failed')),
        raw_payload_id bigint,
        error_message text,
        started_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        completed_at timestamptz,
        UNIQUE (archive_year, archive_sha256, parser_name, parser_version)
    )
    """,
)


class DestinoRemotoRecusado(RuntimeError):
    """Gravacao pedida em banco que nao é o armazem local."""


def exigir_local(engine) -> None:
    """Recusa qualquer destino que nao seja o armazem local.

    Sao ~1 GB de linhas. O Supabase free tem 500 MB e o app publicado depende
    dele; um `--destino` distraido nao pode ser suficiente para derrubar a
    producao.
    """
    if engine is None:
        raise DestinoRemotoRecusado("nenhuma engine informada")
    host = (engine.url.host or "").lower()
    if host and host not in HOSTS_LOCAIS:
        raise DestinoRemotoRecusado(
            f"preco diario da B3 so pode ser gravado no armazem local; "
            f"destino recusado: {host}")


def _parser_hash() -> str:
    """Impressao do codigo que le o arquivo -- este modulo e o leitor."""
    partes = b"".join(Path(arquivo).read_bytes()
                      for arquivo in (__file__, b3_cotahist.__file__))
    return hashlib.sha256(partes).hexdigest()


# Aplicado em tabela que ja existe, onde `CREATE TABLE IF NOT EXISTS` nao chega.
# Idempotente e seguro de rodar em base ja correta.
MIGRACOES = (
    """
    DO $$
    DECLARE nome text;
    BEGIN
        IF to_regclass('market.b3_security_history') IS NULL THEN RETURN; END IF;
        -- Chave antiga: qualquer UNIQUE desta tabela que carregue o sha dentro.
        FOR nome IN
            SELECT conname FROM pg_constraint
             WHERE conrelid = 'market.b3_security_history'::regclass
               AND contype = 'u'
               AND pg_get_constraintdef(oid) ILIKE '%archive_sha256%'
        LOOP
            EXECUTE format('ALTER TABLE market.b3_security_history '
                           'DROP CONSTRAINT %I', nome);
        END LOOP;
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
             WHERE conrelid = 'market.b3_security_history'::regclass
               AND conname = 'b3_security_history_ticker_data_key'
        ) THEN
            ALTER TABLE market.b3_security_history
                ADD CONSTRAINT b3_security_history_ticker_data_key
                UNIQUE (ticker, trade_date);
        END IF;
    END $$;
    """,
)


def garantir_schema(conn) -> None:
    """Cria tabela e indices se faltarem e migra o que ja existe. Idempotente."""
    for ddl in DDL:
        conn.execute(text(ddl))
    for migracao in MIGRACOES:
        conn.execute(text(migracao))


def preparar_linhas(linhas: list[dict]) -> list[dict]:
    """Descarta o que nao tem fechamento e calcula o preco unitario.

    Uma linha sem `close` nao é preco: é papel listado que nao negociou no dia.
    Ela nao entra, do mesmo jeito que nao entra na ingestao de FIIs -- a tabela
    é de preco observado, e ausencia de negocio nao é preco zero.
    """
    saida: list[dict] = []
    for linha in linhas:
        fechamento = linha.get("close")
        if not fechamento or fechamento <= 0:
            continue
        fator = linha.get("fator_cotacao") or 1
        if fator <= 0:
            fator = 1
        saida.append({**linha, "close_unitario": round(fechamento / fator, 6)})
    return saida


def ingerir_ano(engine, ano: int, *, conteudo: bytes | None = None) -> dict:
    """Ingere um ano do COTAHIST. Reentrante: ano ja concluido é ignorado."""
    exigir_local(engine)
    relatorio = {"ano": ano, "status": "completed", "linhas": 0,
                 "tickers": 0, "pulado": False}
    if conteudo is None:
        conteudo, url, headers = fetch_year(ano)
    else:
        url, headers = f"local:COTAHIST_A{ano}.ZIP", {}
    sha = hashlib.sha256(conteudo).hexdigest()

    with engine.begin() as conn:
        garantir_schema(conn)
        concluido = conn.execute(text("""
            SELECT status='completed' FROM market.b3_archive_loads
             WHERE archive_year=:ano AND archive_sha256=:sha
               AND parser_name=:parser AND parser_version=:versao
        """), {"ano": ano, "sha": sha, "parser": PARSER_NAME,
               "versao": PARSER_VERSION}).scalar()
    if concluido:
        _LOGGER.info("COTAHIST %s (lote padrao) ja concluido, ignorado", ano)
        return {**relatorio, "pulado": True}

    linhas = preparar_linhas(b3_cotahist.ler_linhas(conteudo))
    coletado = datetime.now(timezone.utc)
    relatorio["linhas"] = len(linhas)
    relatorio["tickers"] = len({linha["ticker"] for linha in linhas})

    with engine.begin() as conn:
        raw_id = save_raw_payload(
            conn, None, "b3/cotahist/lote-padrao",
            {"ano": ano, "sha256": sha, "linhas": len(linhas),
             "parser": PARSER_NAME, "parser_version": PARSER_VERSION},
            request_params={"year": ano}, response_headers=headers,
            collected_at=coletado, source=SOURCE,
            request_fingerprint=hashlib.sha256(
                f"{url}|{PARSER_NAME}".encode()).hexdigest(),
        )
        conn.execute(text("""
            INSERT INTO market.b3_archive_loads (
                archive_year,archive_sha256,parser_name,parser_version,source_url,
                expected_rows,loaded_rows,status,raw_payload_id,error_message,updated_at
            ) VALUES (:ano,:sha,:parser,:versao,:url,:esperado,0,'running',:raw,NULL,now())
            ON CONFLICT (archive_year,archive_sha256,parser_name,parser_version)
            DO UPDATE SET source_url=EXCLUDED.source_url,
                          expected_rows=EXCLUDED.expected_rows,
                          status='running', raw_payload_id=EXCLUDED.raw_payload_id,
                          error_message=NULL, updated_at=now()
        """), {"ano": ano, "sha": sha, "parser": PARSER_NAME,
               "versao": PARSER_VERSION, "url": url, "esperado": len(linhas),
               "raw": raw_id})

    payload = [{**linha, "source_url": url, "raw_payload_id": raw_id,
                "collected_at": coletado.isoformat(), "archive_sha256": sha}
               for linha in linhas]
    gravadas = 0
    lidas = 0
    for inicio in range(0, len(payload), _BATCH_SIZE):
        lote = payload[inicio:inicio + _BATCH_SIZE]
        with engine.begin() as conn:
            resultado = conn.execute(text("""
                INSERT INTO market.b3_security_history (
                    ticker,trade_date,bdi,issuer_short_name,specification,isin,
                    open,high,low,average,close,fator_cotacao,close_unitario,
                    trades,quantity,financial_volume,source,source_url,
                    raw_payload_id,collected_at,archive_sha256
                ) SELECT ticker,trade_date,bdi,issuer_short_name,specification,isin,
                    open,high,low,average,close,fator_cotacao,close_unitario,
                    trades,quantity,financial_volume,:source,source_url,
                    raw_payload_id,collected_at,archive_sha256
                FROM jsonb_to_recordset(CAST(:linhas AS jsonb)) AS x(
                    ticker text,trade_date date,bdi text,issuer_short_name text,
                    specification text,isin text,open numeric,high numeric,
                    low numeric,average numeric,close numeric,fator_cotacao integer,
                    close_unitario numeric,trades integer,quantity bigint,
                    financial_volume numeric,source_url text,raw_payload_id bigint,
                    collected_at timestamptz,archive_sha256 text
                ) ON CONFLICT (ticker,trade_date) DO UPDATE SET
                    bdi=EXCLUDED.bdi,
                    issuer_short_name=EXCLUDED.issuer_short_name,
                    specification=EXCLUDED.specification, isin=EXCLUDED.isin,
                    open=EXCLUDED.open, high=EXCLUDED.high, low=EXCLUDED.low,
                    average=EXCLUDED.average, close=EXCLUDED.close,
                    fator_cotacao=EXCLUDED.fator_cotacao,
                    close_unitario=EXCLUDED.close_unitario,
                    trades=EXCLUDED.trades, quantity=EXCLUDED.quantity,
                    financial_volume=EXCLUDED.financial_volume,
                    source_url=EXCLUDED.source_url,
                    raw_payload_id=EXCLUDED.raw_payload_id,
                    collected_at=EXCLUDED.collected_at,
                    archive_sha256=EXCLUDED.archive_sha256
                  -- Reingerir um ZIP guardado no cache nao pode rebaixar o que
                  -- veio de uma coleta mais nova: a linha so cede para quem
                  -- chegou depois dela.
                  WHERE EXCLUDED.collected_at >= market.b3_security_history.collected_at
            """), {"source": SOURCE,
                   "linhas": json.dumps(lote, ensure_ascii=False)})
        # Linhas efetivamente escritas, nao o tamanho do lote: com a guarda
        # de `collected_at`, reingerir um arquivo antigo grava menos do que le,
        # e contar o lote esconderia isso atras de um numero redondo.
        gravadas += resultado.rowcount if resultado.rowcount >= 0 else len(lote)
        lidas += len(lote)
        if inicio % (_BATCH_SIZE * 10) == 0 or lidas == len(payload):
            _LOGGER.info("COTAHIST %s — %s/%s linhas", ano, lidas, len(payload))
            with engine.begin() as conn:
                conn.execute(text("""
                    UPDATE market.b3_archive_loads SET loaded_rows=:n, updated_at=now()
                     WHERE archive_year=:ano AND archive_sha256=:sha
                       AND parser_name=:parser AND parser_version=:versao
                """), {"n": gravadas, "ano": ano, "sha": sha,
                       "parser": PARSER_NAME, "versao": PARSER_VERSION})

    with engine.begin() as conn:
        conn.execute(text("""
            UPDATE market.b3_archive_loads
               SET loaded_rows=:n, status='completed', updated_at=now(), completed_at=now()
             WHERE archive_year=:ano AND archive_sha256=:sha
               AND parser_name=:parser AND parser_version=:versao
        """), {"n": gravadas, "ano": ano, "sha": sha,
               "parser": PARSER_NAME, "versao": PARSER_VERSION})
    relatorio["gravadas"] = gravadas
    return relatorio


def ingerir(engine, *, anos: range | None = None,
            cache_apenas: bool = False) -> dict:
    """Ingere um intervalo de anos.

    `cache_apenas` usa somente os ZIPs ja baixados em
    `fii_b3_history.CACHE_ROOT`, sem tocar a rede -- é o modo do backfill, que
    tem 584 MB de arquivo em disco desde julho.
    """
    from data_pipeline.market.fii_b3_history import CACHE_ROOT

    exigir_local(engine)
    corrente = datetime.now(timezone.utc).year
    anos = anos or range(PRIMEIRO_ANO, corrente + 1)
    geral = {"status": "completed", "anos": [], "linhas": 0, "erros": []}
    for ano in anos:
        try:
            conteudo = None
            if cache_apenas:
                caminho = CACHE_ROOT / f"COTAHIST_A{ano}.ZIP"
                if not caminho.exists():
                    geral["erros"].append({"ano": ano, "erro": "ZIP ausente no cache"})
                    continue
                conteudo = caminho.read_bytes()
            relatorio = ingerir_ano(engine, ano, conteudo=conteudo)
            geral["anos"].append(relatorio)
            geral["linhas"] += relatorio["linhas"]
        except Exception as erro:  # noqa: BLE001 - o ano falho nao pode parar os outros
            _LOGGER.exception("Falha no COTAHIST %s", ano)
            geral["erros"].append({"ano": ano, "erro": str(erro)[:500]})
    if geral["erros"]:
        geral["status"] = "partial" if geral["anos"] else "failed"
    return geral
